version: '2'

#"registry-mirrors": ["https://registry.docker-cn.com"]

services:
  db:
    image:  grayzone/pgdb
    restart: always
    container_name: pgdb
    environment: 
      POSTGRES_PASSWORD: 123456
    ports:
     - 5433:5432
#    volumes:
#     - '/svr/pgdb/data:/var/lib/postgresql/data'
  adminer:
    image:  adminer
    restart: always
    container_name: adminer
    ports:
     - 9876:8080    